---
new_page_extension: md
auto_deploy: true
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: dataschool/_chapters
  label: Chapters
  create: all
  match: "**/*.md"
  templates:
  - chapter-template
- type: directory
  path: dataschool/_books
  label: Books
  create: documents
  match: "**/*.md"
  templates:
  - book-template
- type: directory
  path: dataschool/_people
  label: People
  create: documents
  match: "**/*.md"
  templates:
  - people-template
- type: jekyll-pages
  label: Pages
  create: documents
  match: "**/*"
upload_dir: dataschool/assets/images
public_path: "/assets/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
instant_preview: true
build:
  preview_command: bundle exec jekyll build --drafts --unpublished --future -d _site
  publish_command: bundle exec jekyll build -d _site
  preview_env:
  - JEKYLL_ENV=staging
  - RUBY_VERSION=2.6.1
  - BUILD_DIR=dataschool
  publish_env:
  - JEKYLL_ENV=production
  - RUBY_VERSION=2.6.1
  - BUILD_DIR=dataschool
  preview_output_directory: dataschool/_site
  output_directory: dataschool/_site
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
